fix: correct memory layout
rustsbi/serde-device-tree pull request #3
Opened 2024-10-09 12:24 UTC by woshiluo

由于 https://github.com/rustsbi/serde-device-tree/blob/main/src/de_mut/group.rs#L169 中会直接将 `GroupDeserializer<'_>` 拷贝给 `NodeSeq<'de>`，所以需要保证一致的内存布局。

2024-10-09 14:47 UTC, luojia65 commented
r? @YdrMaster

2024-10-09 14:55 UTC, luojia65 requested changes

2024-10-09 14:55 UTC, luojia65 commented on src/de_mut/node_seq.rs
>  pub struct NodeSeq<'de> {
We'd better fix memory layout using `#[repr(C)]` for `NodeSeq` and `GroupDeserializer`.

2024-10-09 15:58 UTC, luojia65 approved these changes
LGTM, please check if the examples (hifive-unmatched-a00.rs, etc.) work as well.

2024-10-10 03:06 UTC, woshiluo commented
![image](https://github.com/user-attachments/assets/cb51dacf-7055-4861-af28-75851189f0ba)

The examples should work normally in this pull request。

2024-10-10 12:35 UTC, merged

2024-10-10 12:35 UTC, luojia65 commented
We should remove #[repr(C)] in upstream as it is no longer necessary for no memory casts are performed; I'll do it.